<?php

// Load the Library and Requirement Hooks
require_once ( dirname(__FILE__) . '/timelinejs_block.library.inc' );
// Load Block hooks
require_once ( dirname(__FILE__) . '/timelinejs_block.block.inc' );

/**
 * Implement hook_menu().
 */
function timelinejs_block_menu() {
  $items['json/%'] = array(
    'title' => t('JSON'),
    'page callback' => 'timelinejs_block_json',
    'page arguments' => array(1),
    'access arguments' => array('access content'),
    'file' => 'timelinejs_block.json.inc',
    'type' => MENU_CALLBACK,
  );
  $items['admin/config/content/timelinejs_config'] = array(
    'title' => t('TimelineJS Configuration'),
    'description' => t('Configuration for TimelineJS'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('timelinejs_block_config_form'),
    'access arguments' => array('access administration pages'),
    'file' => 'timelinejs_block.admin.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}
