<?php

/**
 * Implement hook_menu().
 */
function timelinejs_view_menu() {

  $items['json'] = array(
    'title' => t('rewrite'),
    'page callback' => 'rewrite',
    'access arguments' => array('access administration pages'),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Implement hook_block_info().
 */
function timelinejs_view_block_info(){
  $blocks['timelinejs_view'] = array(
      'info' => t('Display Timeline'),
    );
  return $blocks;
}

/**
 * Implement hook_block_configure().
 */
function timelinejs_view_block_configure($delta){
  $form = array();
  if($delta == 'timelinejs_view'){
    $form['timelinejs_view_headline'] = array(
      '#type' => 'textfield',
      '#title' => t('Headline'),
      '#size' => 60,
      '#description' => t('Headline for timeline'),
      '#default_value' => variable_get('timelinejs_view_headline', 'Headline'),
      '#required' => TRUE,
    );
    $form['timelinejs_view_jsonpath'] = array(
      '#type' => 'textfield',
      '#title' => t('Date JSON Path'),
      '#size' => 60,
      '#description' => t('Full URL for Dates JSON Path'),
      '#default_value' => variable_get('timelinejs_view_jsonpath', 'http://mapping.mdba.gov.au/timeline_json'),
      '#required' => TRUE,
    );
    $form['timelinejs_view_era_jsonpath'] = array(
      '#type' => 'textfield',
      '#title' => t('Era JSON Path'),
      '#size' => 60,
      '#description' => t('Full URL for Era JSON Path'),
      '#default_value' => variable_get('timelinejs_view_era_jsonpath', 'http://mapping.mdba.gov.au/era_json'),
      '#required' => TRUE,
    );
  }
  return $form;
}

/**
 * Implement hook_block_save().
 */
function timelinejs_view_block_save($delta = '', $edit = array()){
  if($delta = 'timelinejs_view'){
    variable_set('timelinejs_view_headline', $edit['timelinejs_view_headline']);
    variable_set('timelinejs_view_jsonpath', $edit['timelinejs_view_jsonpath']);
    variable_set('timelinejs_view_era_jsonpath', $edit['timelinejs_view_era_jsonpath']);
  }
}

function rewrite(){
  //_timelinejs_view_dates_generator();
  $json_file_of_era = variable_get('timelinejs_view_era_jsonpath', 'http://mapping.mdba.gov.au/era_json');

  $era = file_get_contents($json_file_of_era);
  $era = substr($era, 1);
  $era = substr($era, 1, -1);

  $dates = _timelinejs_view_dates_generator();

  $headline = variable_get('timelinejs_view_headline', 'This is a test');

  $timeline = '{"timeline":';
  $timeline .= '{';
  $timeline .= '"headline":"'. $headline .'",';
  $timeline .= '"type":"default",';
  $timeline .= '"text":"<p>Intro parra.</p>",';
  $timeline .= $dates;
  $timeline .= ',"'.$era;
  $timeline .= '}}'; 


  echo($timeline);
}

function _timelinejs_view_dates_generator() {
  $type = 'timelinejs_dates';
  $nodes = node_load_multiple(array(), array('type' => $type));
  $dateJson = '"date":[';
  foreach($nodes as $date){
    $entry = new stdClass(); 
    $entry->startDate = date('Y,m,d', strtotime($date->field_dates['und'][0]['value']));
    $entry->endDate = date('Y,m,d', strtotime($date->field_dates['und'][0]['value2']));
    $entry->headline = $date->title;
    $entry->text = $date->body['und'][0]['safe_value'];
    $entry->text = str_replace(PHP_EOL, '', $entry->text);
    if(isset($date->field_timeline_category['und'][0]['tid'])){
      $entry->tag = taxonomy_term_load($date->field_timeline_category['und'][0]['tid'])->name;
    }
    if(isset($date->field_media_url['und'][0]['value'])){
      $entry->asset->media = $date->field_media_url['und'][0]['value'];
    }
    if(isset($date->field_media_caption['und'][0]['value'])){
      $entry->asset->caption = $date->field_media_caption['und'][0]['value'];
    }
    if(isset($date->field_media_credit['und'][0]['value'])){
      $entry->asset->credit = $date->field_media_credit['und'][0]['value'];
    }
    $dateJson .= '{"startDate":"' . $entry->startDate .'",';
    $dateJson .= '"endDate":"' . $entry->endDate .'",';
    $dateJson .= '"headline":"' . $entry->headline .'",';
    $dateJson .= '"text":"' . $entry->text .'"';

    if(isset($entry->tag)){
      $dateJson .= ',"tag":"' . $entry->tag .'"';
    }

    if(isset($entry->asset->media)){
      $dateJson .= ',"asset":{';
      $dateJson .= '"media":"'.$entry->asset->media.'"';

      if(!isset($entry->asset->caption) && !isset($entry->asset->credit)){
        $dateJson .= '}';
      } elseif(isset($entry->asset->caption)){
          $dateJson .= ',"caption":"'.$entry->asset->caption.'"';
          if(!isset($entry->asset->credit)){
            $dateJson .= '}';
          } else {
            $dateJson .= ',"credit":"'.$entry->asset->credit.'"}';
          }
      } else {
          $dateJson .= ',"credit":"'.$entry->asset->credit.'"}';
        }
    }
    


    if($date === end($nodes)){
      $dateJson .= '}';
    } else {
      $dateJson .= '},';
    }
  }
  $dateJson .= ']';
  //dump($entry);
  //dump($dateJson);
  return $dateJson;

}
