<?php

// Load the Library and Requirement Hooks
require_once ( dirname(__FILE__) . '/timelinejs_block.library.inc' );
// Load Block hooks
require_once ( dirname(__FILE__) . '/timelinejs_block.block.inc' );

/**
 * Implement hook_menu().
 */
function timelinejs_block_menu() {
  $items['json/%'] = array(
    'title' => t('JSON'),
    'page callback' => 'timelinejs_block_json',
    'page arguments' => array(1),
    'access arguments' => array('access content'),
    'file' => 'timelinejs_block.json.inc',
    'type' => MENU_CALLBACK,
  );
  $items['admin/config/content/timelinejs_config'] = array(
    'title' => t('TimelineJS Configuration'),
    'description' => t('Configuration for TimelineJS'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('timelinejs_block_config_form'),
    'access arguments' => array('access administration pages'),
    'file' => 'timelinejs_block.admin.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/**
 * Implement hook_init().
 */
function timelinejs_block_init(){
  // Send X-UA-Compatible HTTP header to force IE to use the most recent
  // rendering engine or use Chrome's frame rendering engine if available.
  if (is_null(drupal_get_http_header('X-UA-Compatible'))) {
    drupal_add_http_header('X-UA-Compatible', 'IE=edge,chrome=1');
  }
}
