<?php

// Load the Library and Requirement Hooks
require_once ( dirname(__FILE__) . '/timelinejs_block.library.inc' );
// Load Block hooks
require_once ( dirname(__FILE__) . '/timelinejs_block.block.inc' );

/**
 * Implement hook_menu().
 */
function timelinejs_block_menu() {
  $items['json/%'] = array(
    'title' => t('JSON'),
    'page callback' => 'timelinejs_block_json',
    'page arguments' => array(1),
    'access arguments' => array('access timelinejs json'),
    'file' => 'timelinejs_block.json.inc',
    'type' => MENU_CALLBACK,
  );
  $items['admin/config/content/timelinejs_config'] = array(
    'title' => t('TimelineJS Configuration'),
    'description' => t('Configuration for TimelineJS'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('timelinejs_block_config_form'),
    'access arguments' => array('access administration pages'),
    'file' => 'timelinejs_block.admin.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/**
 * Implement hook_permisssion().
 */
function timelinejs_block_permission() {
  return array(
    'access timelinejs json' => array(
      'title' => t('Access TimelineJS JSON'),
      'description' => t('View TimelineJS JSON'),
    ),
    'access timelinejs block' => array(
      'title' => t('Access TimelineJS block'),
      'description' => t('View TimelineJS block'),
    )
  );
}

/**
 * Implement hook_init().
 */
function timelinejs_block_init(){
  // Send X-UA-Compatible HTTP header to force IE to use the most recent
  // rendering engine or use Chrome's frame rendering engine if available.
  if (is_null(drupal_get_http_header('X-UA-Compatible'))) {
    drupal_add_http_header('X-UA-Compatible', 'IE=edge,chrome=1');
  }
  $js_path = drupal_get_path('module', 'timelinejs_block').'/scripts/timeline_mod.js';
  $css_path = drupal_get_path('module', 'timelinejs_block').'/css/custom_accessibility.css';
  drupal_add_js($js_path);
  drupal_add_css($css_path);
}
